language: minimal
sudo: required
addons:
  apt:
    packages:
      - docker-ce # use experimental features

services:
  - docker

before_install:
  - docker --version  # document the version travis is using
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
  - sudo service docker restart

jobs:
  include:
    - stage: amd64
      name: Intel/AMD 64-bit (x86_64)
      script:
        - make build-amd64
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - make push-amd64
    - stage: arm64v8
      name: ARMv8 64-bit (modern Raspberry 3+, other 64-bit ARM)
      script:
        - make qemu
        - make build-arm64v8
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - make push-arm64v8
    - stage: arm32v7
      name: ARMv7 32-bit (modern Raspberry Pi 2/3+, ODROID, other 32-bit ARM, usually hard float)
      script:
        - make qemu
        - make build-arm32v7
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - make push-arm32v7
    - stage: manifest
      name: Docker manifest
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - make manifest
